import { NAME } from './constants';

export const FILTER_SERVERS_REQUEST = `${NAME}.FILTER_SERVERS_REQUEST`;
export const FILTER_SERVERS_SUCCESS = `${NAME}.FILTER_SERVERS_SUCCESS`;
export const FILTER_SERVERS_FAILURE = `${NAME}.FILTER_SERVERS_FAILURE`;
export const DISPLAY_CHANGE = `${NAME}.DISPLAY_CHANGE`;
export const SHOW_NEW_SERVERS = `${NAME}.SHOW_NEW_SERVERS`;
export const HEADER_HIDE = `${NAME}.HEADER_HIDE`;
